# Site settings
title: INSERT_SITE_TITLE
description: >
  INSERT_SITE_DESCRIPTION
baseurl: ""
url: "http://*.mlh.io"

# Build settings
markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
